### ISSUE TITLE
Add Restful actions

### ISSUE THREAD

**Issue by tomas-stefano** [tomas-stefano/jeckle#32]
```ruby
class MyApiResource
  include Jeckle::Resource
  api :some_api
  rest_actions except: [:delete]
end
```

## TO DO ##

- [ ] Create rest_actions into module HTTP
- [ ] Add options only and except
- [ ] .find => GET /posts/:id
- [ ] .create => POST /posts
- [ ] #save => POST /posts 
- [ ] #update => PATCH /posts 
- [ ] #destroy => DELETE /posts/:id

**Comment by mateusg** [comment]
To be continued here: #51
